name: Update PR Description
author: nefrob
description: Add or update content in GitHub PR description.

inputs:
    content:
        description: Content to append or replace in the PR body.
        required: true
    contentIsFilePath:
        description: Whether the content is a file path.
        required: false
    regex:
        description: Regex string to match and replace the description.
        required: false
    regexFlags:
        description: Regex flags to use.
        required: false
    replacementRegex:
        description: Regex string for replacing description with only a specific part of the replacement payload (only first match).
        required: false
    replacementRegexFlags:
        description: Regex flags to use.
        required: false
    appendContentOnMatchOnly:
        description: Whether to skip appending the content to the PR body if no regex matches are found.
        default: "false"
    token:
        description: GitHub access token.
        required: true

runs:
    using: node20
    main: dist/index.js

branding:
    icon: align-left
    color: white
