name: Update PR Description
author: nefrob
description: Add or update content in GitHub PR description.

inputs:
  content:
    description: Content to add to PR description.
    required: true
  contentIsFilePath:
    description: Whether the content is a file path or raw text.
    required: false
  regex:
    description: Regex string to match and replace with content. Pass an empty string to append.
    required: false
  regexFlags:
    description: Regex flags to use.
    required: false
  appendContentOnMatchOnly:
    description: Whether to append content to the PR body only when there is a regex match.
    default: "false"
  token:
    description: GitHub secrets access token.
    required: true

runs:
  using: node16
  main: dist/index.js

branding:
  icon: align-left
  color: white